//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH.PriceScope.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPrice
    {
        public int PriceSourceId { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public decimal MinPrice { get; set; }
        public decimal MaxPrice { get; set; }
        public Nullable<decimal> LowCashPrice { get; set; }
        public Nullable<decimal> LowCreditPrice { get; set; }
        public Nullable<decimal> LowCryptoPrice { get; set; }
        public Nullable<decimal> AuctionBid { get; set; }
        public Nullable<System.DateTime> AuctionEndDate { get; set; }
        public Nullable<bool> AuctionReserveMet { get; set; }
        public string ItemSaleUrl { get; set; }
        public string ItemAuctionUrl { get; set; }
    
        public virtual PriceSource PriceSource { get; set; }
    }
}
