//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH.PriceScope.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemPrice
    {
        public int PriceSourceId { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public decimal MinPrice { get; set; }
        public decimal MaxPrice { get; set; }
        public decimal WireCheckPrice { get; set; }
        public decimal CCPaypalPrice { get; set; }
        public decimal BitcoinPrice { get; set; }
        public string ItemUrl { get; set; }
    
        public virtual PriceSource PriceSource { get; set; }
    }
}
