//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH.PriceScope.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purity
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int MetalId { get; set; }
    
        public virtual Metal Metal { get; set; }
    }
}
