//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JH.PriceScope.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceParameter
    {
        public int SourceId { get; set; }
        public string ParamKey { get; set; }
        public string ParamValue { get; set; }
    
        public virtual Source Source { get; set; }
    }
}
